# https://github.com/actions/labeler
#wip:
#  - title: "^WIP:.*"
changelog_unchanged:
  - all: ["!CHANGELOG.md"]
no_tests:
  - all: ["!spec/*.rb", "!spec/", "!spec/**/*.rb", "!spec/**/**/*.rb", "!spec/**/**/**/*.rb", "!spec/**/**/**/**/*.rb"]
