# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '8e7b5cac7f7db22ec6d6c615eed3f4e2'
  config.secret_key = 'a2c8b39ce7490aa6c0e28451c7c719ac'
  config.default_from = 'orest.f@coaxsoft.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
end
