development:
  adapter: any_cable
  url: <%= RCreds.fetch(:redis_url, default: 'redis://localhost:6379/1') %>
  channel_prefix: estimator_v2_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= RCreds.fetch(:redis_url, default: 'redis://localhost:6379/1') %>
  channel_prefix: estimator_v2_production
